import "./globals.css";
import { Plus } from "lucide-react";
import { Navbar } from "./ui/Navbar";
import Link from "next/link";
import { Toaster } from "sonner";
import Button from "./ui/Button";
export const metadata = {
  title: "TakeControl",
  description: "Generated by create next app",
};

export default function RootLayout({ modal, children }) {
  return (
    <html lang="en">
      <body>
        <Navbar>
            <h1>Project Take Control</h1>
            <div>
              <Link href="/create-project">
                <Button variant = "default">
                  <Plus /> 
                  Project
                </Button>
              </Link>
            </div>
        </Navbar>
        {children}
        <div style={{paddingLeft: "2rem"}} >
        </div>
        
        {modal}
        <Toaster richColors />
      </body>
    </html>
  );
}
