import "./globals.css";
import {Navbar} from "./ui/Navbar";

export const metadata = {
  title: "Takcontrol",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar>
            <h1>Project Take Control</h1>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
